scrartcl - versatile class may be used as a drop-in replacement of article
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrartcl is a LaTeX class of the KOMA-Script bundle. It is
                the KOMA-Script drop-in replacement for the standard LaTeX
                article class. It provides all options, environments,
                counters, lengths and commands of the standard LaTeX article
                class, as well as several additional options, environments,
                commands, etc. to make it much more versatile. The default
                layout of scrartcl differs from article, with an emphasis on
                good typography. Nevertheless, by changing the defaults, you
                can achieve a layout very similar to that of the standard
                class.
Requires:       scrkbase - internal KOMA-Script package
                tocbasic - KOMA-Script package
                typearea - KOMA-Script package
Recommended:    scrlayer-scrpage - KOMA-Script package
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
