scrbook - versatile class may be used as a drop-in replacement of book
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrbook is a LaTeX class of the KOMA-Script bundle and a
                drop-in replacement for the standard LaTeX book class. It 
                provides all options, environments, commands, etc. of the
                standard LaTeX book class, as well as several additional 
                options, environments, commands, etc. to make it much more
                versatile. The default layout of scrbook differs from book,
                with an emphasis on good typography. Nevertheless, by changing
                the defaults, you can achieve a layout very similar to that
                of the standard class.
Requires:       scrkbase - internal KOMA-Script package
                tocbasic - KOMA-Script package
                typearea - KOMA-Script package
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
