scrbook - versatile class may be used as a drop-in replacement of book
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrbook is a LaTeX class of the KOMA-Script bundle and a
                drop-in replacement of LaTeX standard class book.  It 
                provides all options, environments, commands, etc. of the
                LaTeX standard class book, but also several additional 
                options, environments, commands etc. to make it much more
                versatile.  The default layout of scrbook differs from book
                with emphasis on typography.  Nevertheless by changing the
                defaults a layout very similar to the layou of the standard
                class may be accomplished.
Requires:       scrkbase - internal KOMA-Script package
                tocbasic - KOMA-Script package
                typearea - KOMA-Script package
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
