scrdoc - internal source documentation class of KOMA-Script
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrdoc is an internal LaTeX class of the KOMA-Script bundle.
                It is an extension of ltxdoc.  KOMA-Script uses scrdoc for
                the implementation documentation and the documentation of
                packages that aren't KOMA-Script core packages.  Currently
                there is no user manual for this class because the
                only user is the KOMA-Script maintainer.
Requires:       ltxdoc   - the LaTeX2e source documentation class
                scrartcl - the KOMA-Script article class
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
