scrartcl - versatile class may be used as a drop-in replacement of article
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrartcl is a LaTeX class of the KOMA-Script bundle.  It is
                the KOMA-Script drop-in replacement of LaTeX standard class
                article.  It provides all options, environments, counters,
                lengths and commands of the LaTeX standard class article, but
                also several additional options, environments, commands
                etc. to make it much more versatile.  The default layout of
                scrartcl differs from article with emphasis on typography.
                Nevertheless by changing the defaults a layout very similar to
                the layou of the standard class may be accomplished.
Requires:       scrkbase - internal KOMA-Script package
                tocbasic - KOMA-Script package
                typearea - KOMA-Script package
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
