scrletter - wrapper class to scrlttr2
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrreport is a very simple wrapper class to scrlttr2. Is has
                been made, because several younger KOMA-Script users doe not
                understand the 8.3 name scheme.

                However it is still recommended to use scrlttr2 instead of
                scrletter.
Requires:       scrlttr2.cls - KOMA-Script class
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
