scrlttr2 - versatile letter class with separation of text area and note paper
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrlttr2 is a letter class for LaTeX2e that allows
                definition of several letterheads and text area settings
                that are independent from the letterhead. So you can use
                not only the KOMA-Script package typearea but even packages
                like geometry to define the text area and the margins.

                The positions of the elements of the letterhead can be
                changed by so called pseudo-lengths. This makes it possible
                to adjust scrlttr2 not only to local conventions and paper
                sizes but also to a corporate brand identity.

                Several predefined sets of parameters, called
                letter-class-option or lco files are part of the
                KOMA-Script bundle: two German letters, Swiss letters, US
                letters, Japanese letters, and French letters.  More can be
                found on CTAN or the KOMA-Script homepage as separate
                packages.

                Additional lco-files for different letterheads can be found
                on the KOMA-Script homepage, e.g., one demonstration file
                for a letterhead similar to that of Washington State
                University.
Requires:       scrkbase - internal KOMA-Script package
                typearea - KOMA-Script package
Recommended:    marvosym - package by Martin Vogel providing symbols
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
