scrlttr2 - versatil letter class with separation of text area and note paper
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrlttr2 is a letter class for LaTeX2e that allows definition
                of several note papers and text area settings, that are
                independent from the note paper.  So you may not only use
                KOMA-Script package typearea to define the text area and the
                margins of the text area, but even packages like geometry.

                The positions of the elements of the note paper may be changed
                by so called pseudo lengths. This makes it not only possible
                to adjust scrlttr2 to local conventions, norms and paper sizes
                but also to a wanted corporate identity.

                Several predefined parameter sets, called letter class option
                or lco-files, are for two German letters, Swiss letters, US
                letters, Japanese letters, and French letters are part of the
                KOMA-Script bundle. More may be found on CTAN or the
                KOMA-Script homepage as separate packages.

                Additional lco-files for different note papers may be found on
                the KOMA-Script homepage, e.g. one demonstration file for a
                note paper similar to the one of the Washington State
                University.
Requires:       scrkbase - internal KOMA-Script package
                typearea - KOMA-Script package
Recommended:    marvosym - package by Martin Vogel providing symbols
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
