scrarticle - wrapper class to scrartcl
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrreport is a very simple wrapper class to scrartcl. Is has
                been made, because several younger KOMA-Script users doe not
                understand the 8.3 name scheme.

                However it is still recommended to use scrartcl instead of
                scrarticle.
Requires:       scrartcl.cls - KOMA-Script class
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
